// post는 IT-자격-노트/posts 폴더 이름(답안 연습 데이터를 여기서 뽑는다). 공개한 토픽만 넣는다(예정 토픽은 넣지 않는다). 공개하면 url(블로그), video(유튜브), thumb(썸네일), summary(정의 1~2문장)를 채운다. url이 있는 것만 공개 토픽으로 보인다.
window.TOPICS = [
  {"date": "2026-10-05", "domain": "AI", "cat": "정보관리기술사", "topic": "RAG(검색 증강 생성)", "point": "정의, 구성(임베딩·벡터DB·검색·생성), 파인튜닝과 비교, 환각 줄이는 원리", "post": "01-rag", "url": "https://kj84xen.tistory.com/15", "video": "https://youtu.be/bD_U08iG0lY", "thumb": "img/thumbs/rag.jpg", "short": "RAG", "sub": "검색 증강 생성", "summary": "질문과 관련된 외부 문서를 먼저 찾아 프롬프트에 붙이고, LLM이 그 근거로 답하게 하는 구조다. 모델을 다시 학습시키지 않고 최신 지식을 반영한다."},
  {"date": "2026-10-06", "domain": "DB·데이터", "cat": "SQLP", "topic": "실행계획 읽는 법", "post": "02-plan", "url": "https://kj84xen.tistory.com/16", "video": "https://youtu.be/OkctI4M3Di4", "thumb": "img/thumbs/plan.jpg", "summary": "옵티마이저가 통계정보로 비용을 계산해 고른 액세스 경로, 조인 순서, 조인 방식을 트리로 나타낸 것이다. 예상과 실측을 비교해 카디널리티 오추정을 찾는 것이 튜닝의 출발점이다."},
  {"date": "2026-10-06", "domain": "IT경영", "cat": "정보시스템감리사", "topic": "정보시스템 감리 개요와 감리 시점", "post": "03-audit", "url": "https://kj84xen.tistory.com/17", "video": "https://youtu.be/lOOhj16Jcvc", "thumb": "img/thumbs/audit.jpg", "summary": "발주자와 사업자 이외의 제3자가 정보시스템 구축 사업을 단계별로 점검하고 시정을 요구하는 제도다. 요구정의, 설계, 종료 단계에서 점검하고 시정조치 결과까지 확인한다."},
  {"date": "2026-10-07", "domain": "SW공학", "cat": "정보관리기술사", "topic": "MSA와 모놀리식 비교", "post": "04-msa", "url": "https://kj84xen.tistory.com/18", "video": "https://youtu.be/dYC2M5-VmjM", "thumb": "img/thumbs/msa.jpg", "summary": "애플리케이션을 비즈니스 기능 단위의 작은 서비스로 나눠 따로 개발하고 배포하고 확장하는 아키텍처다. 독립 배포를 얻는 대신 분산 데이터 일관성과 운영 복잡도라는 비용을 치른다."},
  {"date": "2026-10-07", "domain": "보안", "cat": "정보관리기술사", "topic": "제로 트러스트 보안", "post": "05-zerotrust", "url": "https://kj84xen.tistory.com/19", "video": "https://youtu.be/-dWbZUtz1js", "thumb": "img/thumbs/zerotrust.jpg", "summary": "네트워크 위치만으로 신뢰를 주지 않고 자원에 접근할 때마다 신원, 기기 상태, 맥락을 다시 검증하는 보안 모델이다. NIST SP 800-207이 PE·PA·PEP 구조로 정리했다."},
  {"date": "2026-10-08", "domain": "DB·데이터", "cat": "SQLP", "topic": "조인 방식 비교 (NL, Sort Merge, Hash)", "post": "06-join", "url": "https://kj84xen.tistory.com/20", "video": "https://youtu.be/17witNXV-7A", "thumb": "img/thumbs/join.jpg", "summary": "두 집합을 실제로 결합하는 물리적 알고리즘으로 NL, 소트 머지, 해시 조인이 대표적이다. 데이터 양, 인덱스, 조인 조건에 따라 같은 SQL의 성능이 크게 달라진다."},
  {"date": "2026-10-08", "domain": "AI", "cat": "정보관리기술사", "topic": "과적합과 정규화(Overfitting·Regularization)", "post": "07-overfitting", "url": "https://kj84xen.tistory.com/21", "video": "https://youtu.be/KoJEMQL3EYs", "thumb": "img/thumbs/overfitting.jpg", "summary": "학습 데이터에는 잘 맞지만 처음 보는 데이터에서 성능이 무너지는 현상이다. 정규화, 드롭아웃, 조기 종료, 데이터 증강으로 모델이 외우지 않고 일반화하게 만든다."},
  {"date": "2026-10-09", "domain": "SW공학", "cat": "정보관리기술사", "topic": "애자일과 스크럼", "post": "08-scrum", "url": "https://kj84xen.tistory.com/22", "video": "https://youtu.be/FSgQLHkcDpI", "thumb": "img/thumbs/scrum.jpg", "summary": "짧게 만들고 자주 보여 주면서 계획을 계속 고쳐 가는 개발 방식이다. 스크럼은 이를 스프린트, 정해진 역할, 이벤트로 굴리는 대표 프레임워크다."},
  {"date": "2026-10-09", "domain": "보안", "cat": "정보관리기술사", "topic": "전자서명과 PKI", "post": "09-pki", "url": "https://kj84xen.tistory.com/23", "video": "https://youtu.be/J13e1PlVDtQ", "thumb": "img/thumbs/pki.jpg", "summary": "전자서명은 개인키로 문서에 찍는 도장이고, PKI는 그 공개키의 주인을 인증기관이 인증서로 보증하는 체계다. 위조 방지, 무결성, 부인 방지를 함께 얻는다."},
];
